### PR TITLE
added peek() to Stack and added corresponding test in StackTest

### PR DESCRIPTION
**Pull request by gansai**

### CODE REVIEW

**Comment by ashish-chopra** [comment]
Hi Gansai,

Thanks for your contribution into the data structure. But Stack data structure is in "Structures" repository and you sent the pull request to "Doodle" repository. Can you resend the request for "Structures" repo? I will merge it, then.

Thanks!
Ashish

**Comment by ashish-chopra** [comment]
Hi Gansai,

I am also migrating the Structures project to Maven, if you want, you can use that branch to send your code. The branch is "maven-migration-dev" in "Structures" repo.

Cheers
Ashish

**Comment by gansai** [comment]
Hi Ashish,

I found only two branches for Structures repo- master and v1.0-release. I could not find maven-migration-dev branch. Please clarify. Thanks. (So, I shall send a pull request to migration-dev branch then, once I am able to find that branch with your help)

Cheers,
Ganesh

**Comment by ashish-chopra** [comment]
Hi Gansai,

I saw doodle, and found that stack was also present there. So i merged your
code in there.

Yesterday i was converting Structures repo into maven project in
maven-migration-dev branch which completed late in the night, so i
successfully merged the branch into master and closed it. Now you can take
latest pull of master branch of Structures and submit peek code in that too.

I removed my inhouse testing framework and now used junits. So it becomes
more easy to write test cases.

In case you encounter any new data structure in future, keep sending patch
to add it in the repo!!

Thanks
Ashish

**Comment by gansai** [comment]
Thanks Ashish. Will do that definitely.
Cheers,
Ganesh

**Pull request merged**
